# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

[GLOBAL]
pants_version = "2.16.0"

# List v2 backends here.
backend_packages.add = [
  'pants.backend.awslambda.python',
  'pants.backend.codegen.protobuf.python',
  'pants.backend.python',
  'pants.backend.python.lint.docformatter',
  'pants.backend.python.lint.black',
  'pants.backend.python.lint.flake8',
  'pants.backend.python.lint.isort',
]

# List plugins here.
plugins = []

[source]
# The Python source root is the repo root. See https://pants.readme.io/docs/source-roots.
root_patterns = [
    "src/python/binary_project1/src",
    "src/python/binary_project1/tests",
    "src/python/binary_project2",
    "src/python/library_project1/src",
    "src/python/library_project1/tests",
    "src/python/setuppy_project1/src",
    "src/python/setuppy_project1/tests",
]

[python]
# The default interpreter compatibility for code in this repo. Individual targets can ovverride
#  this with the `compatibility` field. See
#  https://pants.readme.io/docs/python-interpreter-compatibility.
interpreter_constraints = [">=3.7"]
enable_resolves = true
resolves = { python-default = "python-default.lock"}

[flake8]
config = ".flake8"

[isort]
config = [".isort.cfg"]

#[pytest]
#args = ["-v"]
#version = "pytest>=5.4"
#pytest_plugins.add = [
#  "pytest-icdiff",
#  "pygments",
#]
#junit_xml_dir = "dist/pytest_results"
