


python_distribution(
    name = 'library1',
    wheel=True,
    sdist=True,
    dependencies = [
    ],
    provides=setup_py(
        name="library1",
        version="0.0.1",
        description="Library test 1",
    ),
)

