


python_tests(
    # name defaults to the name of the directory the BUILD file is in `tests`
    # sources defaults to ['*_test.py', 'test_*.py', 'conftest.py'].
    dependencies = [
        "src/python/library_project2/src:library2",
    ]
)

python_test_utils(
    name="test_utils",
)
